accept: "image/jpeg,image/gif,image/png, image/jpg"
open: "Open"
intern: "Intern"
practice: "Practice"
git: "git"
ruby: "ruby"
rails: "rails"
admin: "Admin"
trainer: "Trainer"
trainee: "Trainee"
password: "123456"
